### ISSUE TITLE
微博链接，无法正确获取标题

### ISSUE THREAD

**Issue by seacatwu** [WeepingDogel/TitleGetter#4]
抓出来的都是
Title: Sina Visitor System
不知道该如何解决

**Comment by WeepingDogel** [comment]
解决不了，新浪微博是需要登陆查看的

**Comment by WeepingDogel** [comment]
如果有人能够解决，欢迎pr~

**Comment by WeepingDogel** [comment]
已发现问题，正在尽力解决

**Comment by seacatwu** [comment]
把ua改成移动端，就可以获取正确的标题了

**Comment by WeepingDogel** [comment]
> 把ua改成移动端，就可以获取正确的标题了

真的吗？

**Comment by seacatwu** [comment]
我那天就是改了UA就搞定了这个问题

**Comment by WeepingDogel** [comment]
> 我那天就是改了UA就搞定了这个问题

好耶

**Comment by WeepingDogel** [comment]
> 我那天就是改了UA就搞定了这个问题

请问你将 UA 修改成了什么？

可以给我看看吗

**Comment by WeepingDogel** [comment]
另外，issue 可以关掉吗

**Comment by WeepingDogel** [comment]
经过我的测试，UA 改为移动端爬出来不再是
```
Title: Sina Visitor System
```
但是，爬出来的也只是最开始得到的标题，并不是它具体文章的标题，因此仍然需要改进
```
Title: 微博
```
```
Title: 头条文章
```

**Comment by seacatwu** [comment]
我估计搞错了，我之前的目的是测试微博是否被删除。所以主要是甄别出错信息。
看到你的回复后，我没有验证，以为我的需求达成了就是获取到了正确标题。
不过不管怎么说，这确实是个问题

**Comment by WeepingDogel** [comment]
> 我估计搞错了，我之前的目的是测试微博是否被删除。所以主要是甄别出错信息。
> 看到你的回复后，我没有验证，以为我的需求达成了就是获取到了正确标题。
> 不过不管怎么说，这确实是个问题

好吧好吧 

你的需求只是看看微博是否被删？

**Comment by seacatwu** [comment]
是的，很特殊测一个需求。
